/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104925-ga8a7c5d502-20211218"
#endif /* AVUTIL_FFVERSION_H */
